"""autogeneration

Revision ID: d07ae0366067
Revises: 2216f3cb4f9c
Create Date: 2023-12-10 21:49:10.681187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd07ae0366067'
down_revision: Union[str, None] = '2216f3cb4f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alchemySubstances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('molecular_formula', sa.String(), nullable=False),
    sa.Column('molar_mass', sa.Float(), nullable=False),
    sa.Column('cas', sa.String(), nullable=False),
    sa.Column('sga_classified', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('hazardous_reactions', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('substance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['substance_id'], ['alchemySubstances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'substance_id')
    )
    op.drop_table('basket_a')
    op.drop_table('basket_b')
    op.drop_table('Basic substances')
    op.drop_table('Substances')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Substances',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Substances_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('formula', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Substances_pkey')
    )
    op.create_table('Basic substances',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('molecular_formula', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('molar_mass', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('cas', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Basic substances_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('sga_classified', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Basic substances_pkey')
    )
    op.create_table('basket_b',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fruit_b', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='fruits_b_pkey')
    )
    op.create_table('basket_a',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fruit_a', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='fruits_a_pkey')
    )
    op.drop_table('votes')
    op.drop_table('alchemySubstances')
    op.drop_table('users')
    # ### end Alembic commands ###
