name: Build and deploy code
on:
 push:
   branches: ["main"]
jobs:
 test:
   environment: env
   env:
     DBHOSTNAME: ${{ secrets.DBHOSTNAME }}
     db_port: ${{ secrets.DB_PORT }}
     DBUSERNAME: ${{ secrets.DBUSERNAME }}
     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
     DBNAME: ${{ secrets.DB_NAME }}
     skey: ${{ secrets.SKEY }}
     algorithm: ${{ secrets.ALGORITHM }}
     token_time: ${{ secrets.TOKEN_TIME }}
   runs-on: ubuntu-latest
   services:
     postgres:
       image: postgres
       env:
         POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
         POSTGRES_DB: ${{secrets.DB_NAME}}
       ports:
       - 5432:5432
       options: >-
         --health-cmd pg_isready
         --health-interval 10s
         --health-timeout 5s
         --health-retries 5
   steps:
     - name: pulling repository
       uses: actions/checkout@v4
     - name: Setting up python
       uses: actions/setup-python@v5
       with:
         python-version: '3.10' 
     - name: upgrade pip
       run: python -m pip install --upgrade pip
     - name: install all dependencies
       run: python -m pip install -r requirements.txt
     - name: Add parent directory to PYTHONPATH
       run: echo "export PYTHONPATH=$PYTHONPATH:/home/runner/work/APIChemicalSubstances/APIChemicalSubstances" >> $GITHUB_ENV
     - name: install pytest
       run: python -m pip install pytest
     - name: run pytest
       run: pytest
 deploy:
   name: Deploy
   needs: [test]
   runs-on: ubuntu-latest
   steps:
     - name: Deploy to production
       uses: johnbeynon/render-deploy-action@v0.0.8
       with:
         service-id: ${{ secrets.RENDER_SERVICE_ID }}
         api-key: ${{ secrets.RENDER_API_KEY }}
