name: Build and deploy code
on:
    push:
        branches: ["main"]
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: pulling repository
              uses: actions/checkout@v4
            - name: Setting up python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10' 
            - name: upgrade pip
              run: python -m pip install --upgrade pip
            - name: install all depedencies
              run: python pip install -r requirements.txt